
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udeebd?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLBDialect
      driverClassName: com.mysql.cj.jdbc.Driver
    database: mysql